version: "3"

services:
  database:
    container_name: "${PROJECT_NAME}_database"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./dumps:/dumps

  mailhog:
    container_name: "${PROJECT_NAME}_mailhog"
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
