import type { Collections } from '@/lib/types';
export declare const client: import("@directus/sdk/dist/client-572f0a81").D<Collections> & import("@directus/sdk/dist/login-824b07b5").e<Collections> & import("@directus/sdk/dist/login-824b07b5").S<Collections>;
export declare const fetchSettings: () => Promise<import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<object & import("@/lib/types").Setting, "robots_index" | "meta_title" | "meta_description", import("@directus/sdk/dist/output-68f47924").aF<Collections, object & import("@/lib/types").Setting>>, {
    favicon: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, Readonly<"id" | "width" | "height">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, Readonly<"id" | "width" | "height">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}> | null;
    meta_image: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, Readonly<"id" | "width" | "height">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, Readonly<"id" | "width" | "height">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}> | null;
}>>;
export declare const fetchMetaInformation: (id: number | undefined) => Promise<import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<object & import("@/lib/types").PagesTranslation, "meta_title" | "meta_description", import("@directus/sdk/dist/output-68f47924").aF<Collections, object & import("@/lib/types").PagesTranslation>>, {
    meta_image: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, keyof import("@/lib/types").DirectusFile, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").DirectusFile, keyof import("@/lib/types").DirectusFile, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").DirectusFile>>, {}> | null;
}> | undefined>;
export declare const fetchMainMenu: () => Promise<import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<object & import("@/lib/types").MainMenu, never, import("@directus/sdk/dist/output-68f47924").aF<Collections, object & import("@/lib/types").MainMenu>>, {
    translations: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuTranslation, "title" | "languages_code", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuTranslation>>, {
        nodes: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuNode, "title" | "type" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuNode>>, {
            anchor: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}> | null;
            linked_page: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}> | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuNode, "title" | "type" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuNode>>, {
            anchor: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}> | null;
            linked_page: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}> | null;
        }>[] | null;
    }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuTranslation, "title" | "languages_code", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuTranslation>>, {
        nodes: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuNode, "title" | "type" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuNode>>, {
            anchor: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}> | null;
            linked_page: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}> | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").MainMenuNode, "title" | "type" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").MainMenuNode>>, {
            anchor: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, keyof import("@/lib/types").Section, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {}> | null;
            linked_page: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, keyof import("@/lib/types").PagesTranslation, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {}> | null;
        }>[] | null;
    }>[] | null;
}>>;
export declare const fetchPages: () => Promise<(import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, "id" | "title" | "show_title" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {
    sections: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslationsSection, never, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslationsSection>>, {
        sections_id: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }> | null;
    }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslationsSection, never, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslationsSection>>, {
        sections_id: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }> | null;
    }>[] | null;
}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslation, "id" | "title" | "show_title" | "url", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslation>>, {
    sections: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslationsSection, never, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslationsSection>>, {
        sections_id: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }> | null;
    }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").PagesTranslationsSection, never, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").PagesTranslationsSection>>, {
        sections_id: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").Section, "slug" | "color" | "section_styles", import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").Section>>, {
            blocks: import("@directus/sdk/dist/output-68f47924").au<import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}, import("@directus/sdk/dist/output-68f47924").a5<import("@/lib/types").SectionsBlock, Readonly<"id" | "collection" | "item">, import("@directus/sdk/dist/output-68f47924").aF<Collections, import("@/lib/types").SectionsBlock>>, {}>[] | null;
        }> | null;
    }>[] | null;
}> | undefined)[]>;
